import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const clash = localFont({
  src: "./ClashDisplay-Semibold.otf",
  variable: "--font-clash",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={cn(
          "bg-slate-950 text-white max-w-[800px] mx-auto dark font-default",
          clash.variable,
          inter.variable
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
